<a href="https://colab.research.google.com/github/Tensor-Reloaded/Neural-Networks-Template-2025/blob/main/Lab01/Lab01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Python fundamentals

### Data types

In [1]:
a = 5
print(type(a))

<class 'int'>


In [2]:
a = 5.0
print(type(a))

<class 'float'>


In [3]:
a = '5'
print(type(a))

<class 'str'>


In [4]:
a = True
print(type(a))

<class 'bool'>


## Containers

In [5]:
a_list = [1, 2, 2, 3.0, '5']
print(a_list)
print(type(a_list))

[1, 2, 2, 3.0, '5']
<class 'list'>


In [6]:
a_set = set(a_list)
print(a_set)
print(type(a_set))
a_set = {1, 2, 3, 4}
print(a_set)

{1, 2, 3.0, '5'}
<class 'set'>
{1, 2, 3, 4}


In [7]:
a_dict = {
    1: 'unu',
    'doi': 2,
    3.0: a_set
}
print("Keys:\t", list(a_dict.keys()))
print("Values:\t", list(a_dict.values()))
print(a_dict)
print(type(a_dict))

Keys:	 [1, 'doi', 3.0]
Values:	 ['unu', 2, {1, 2, 3, 4}]
{1: 'unu', 'doi': 2, 3.0: {1, 2, 3, 4}}
<class 'dict'>


## Functions

In [8]:
def add_two_values(a, b):
    return a + b

add_two_values(5, 6)

11

In [9]:
def multiply(a: float, b: float) -> float:
    return a * b

multiply(4.0, 5.0)

20.0

In [10]:
multiply("AB", 2)

'ABAB'

# Numpy

Check: https://numpy.org/doc/stable/user/absolute_beginners.html

### Installing 3rd party libraries

In [11]:
%pip install numpy

In [12]:
%pip install timed-decorator

In [4]:
import numpy as np
from math import sqrt
from timed_decorator.simple_timed import timed

In [13]:
x = np.random.uniform(low=-5.5, high=5.5, size=(50,))
x

array([ 1.34347633,  0.4387629 , -1.16003712,  0.4450906 , -2.26103336,
       -4.65157163, -4.13459252,  3.18999689, -2.2727706 , -1.49936221,
       -4.33576408,  1.73848521, -2.59327242,  4.99664645, -3.98414967,
       -1.06511238, -0.03413635, -1.86572034, -4.721872  ,  4.03409547,
        2.54930698, -3.50200123, -1.75110489,  5.33132536, -1.39352206,
       -5.30485403,  3.74915832, -2.32871572,  1.03309804,  1.89317305,
        3.03656475, -3.31085811, -1.20197928, -2.75604284,  0.07341992,
       -5.14618201, -1.87105993,  3.54970956,  4.85393076, -0.2493299 ,
       -0.13751458, -0.11860276,  4.41472131, -3.11062962, -2.41013309,
       -1.16117053, -5.12594683,  2.43007148,  4.13127681, -5.15805526])

In [15]:
x > 0

array([False,  True, False,  True,  True,  True, False,  True, False,
       False, False,  True, False, False,  True,  True, False, False,
       False, False,  True,  True,  True, False,  True, False, False,
        True, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True, False, False, False, False, False,
       False,  True, False,  True,  True])

In [16]:
x[x > 0]

array([3.55174233, 0.63476826, 1.32473059, 3.25703386, 0.56524522,
       4.98782961, 2.05677049, 0.07322086, 4.25927931, 3.96061448,
       1.87208983, 5.1911797 , 2.74462889, 1.40324877, 1.47291849,
       4.53722535, 0.61056549, 0.49667307, 1.00205239, 0.90775139,
       2.1425354 , 3.00139925, 0.08148065])

In [6]:
list(x)

[np.float64(0.46611735613362004),
 np.float64(0.5634825487475341),
 np.float64(-1.2245252269628315),
 np.float64(2.5477092000132764),
 np.float64(2.2953601849379375),
 np.float64(1.358123147190458),
 np.float64(4.861283025178215),
 np.float64(-0.2734069685813214),
 np.float64(3.6715864097808133),
 np.float64(4.919272165979839),
 np.float64(4.6491272404293955),
 np.float64(-3.10259399567736),
 np.float64(-3.5388707960684225),
 np.float64(-3.933000207241278),
 np.float64(5.457692815195134),
 np.float64(4.282691231627034),
 np.float64(-2.210773100015936),
 np.float64(-4.6360675224160515),
 np.float64(0.32863673760512313),
 np.float64(-0.16332669489121532),
 np.float64(2.017457816907232),
 np.float64(-2.770364472829161),
 np.float64(4.567545797076164),
 np.float64(-4.3648869307830775),
 np.float64(-2.4438510542573573),
 np.float64(-4.349832501552576),
 np.float64(3.49566199213678),
 np.float64(0.9536550019097598),
 np.float64(-1.8273569979251159),
 np.float64(-0.31582204635865896),
 np.flo

## Comparing numpy arrays to python lists

In [16]:
@timed(show_args=True, use_seconds=True)
def normalize_np(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    return (x - mean) / std

@timed(show_args=True, use_seconds=True)
def normalize_py(x: list) -> list:
    mean = sum(x) / len(x)
    var = sum([(i - mean) ** 2 for i in x]) / len(x)
    std = sqrt(var)
    return [(i - mean) / std for i in x]

x = np.random.uniform(low=-5.5, high=5.5, size=(50000,)).astype(np.float64)
y = list(x)
normalized_x = normalize_np(x)
normalized_y = normalize_py(y)
assert np.allclose(normalized_x, normalized_y)

normalize_np(ndarray(50000,)) -> total time: 0.000709500s
normalize_py(list(float64)[50000]) -> total time: 0.024755200s


#### Python is slower than numpy in general

In [17]:
%%timeit

np.min(x)

12.9 μs ± 914 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
%%timeit

min(y)

979 μs ± 28.6 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [20]:
a = np.random.uniform(low=-5.5, high=5.5, size=(50,)).astype(np.float64)
b = list(a)


In [21]:
%%timeit

np.min(a)

4.16 μs ± 194 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [22]:
%%timeit

min(b)

1.08 μs ± 96 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


## Inplace operations
Use them when you can safely modify the input

In [23]:
@timed(show_args=True, use_seconds=True)
def normalize_np_(x: np.ndarray) -> np.ndarray:
    mean = np.mean(x)
    std = np.std(x)
    x -= mean
    x /= std
    return x

In [25]:
x = np.random.rand(1000, 20000)

# This creates a copy
y = normalize_np(x)
assert not np.allclose(x, y)

# Inplace operations modify the original array! But they are faster and use less memory.
z = normalize_np_(x)
assert np.array_equal(x, z)

normalize_np(ndarray(1000, 20000)) -> total time: 0.335128100s
normalize_np_(ndarray(1000, 20000)) -> total time: 0.233667800s
